name: sccache demo

on: [push]

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Configure sccache
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

      - name: Build
        shell: bash
        run: |
          cmake \
            -B build \
            -G "Visual Studio 17 2022" \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_C_COMPILER_LAUNCHER=sccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake \
            --build build \
            --config Release
