name: sccache demo

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
    SCCACHE_GHA_ENABLED: "true"
    CMAKE_BUILD_DIR: "./build"
    GH_TOKEN: ${{ github.token }}

jobs:
    Build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set CMake Build Cache Keys
              shell: bash
              run: |
                  chmod +x ./.github/workflows/find-ideal-cache-key.sh
                  ./.github/workflows/find-ideal-cache-key.sh "windows-latest" "${{ github.base_ref }}"
                  echo "CMAKE_BUILD_CACHE_RESTORE_KEY=$(cat ./restore.cachekey)" >> $GITHUB_ENV
                  echo "CMAKE_BUILD_CACHE_SAVE_KEY=$(cat ./save.cachekey)" >> $GITHUB_ENV

            - name: CMake Build Cache
              id: cmake-build-cache
              uses: actions/cache/restore@v4
              with:
                path: ${{ env.CMAKE_BUILD_DIR }}
                key: ${{ env.CMAKE_BUILD_CACHE_RESTORE_KEY }}

            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.5

            - name: Generate
              shell: bash
              run: |
                  cmake \
                    -B${{ env.CMAKE_BUILD_DIR }} \
                    -DCMAKE_BUILD_TYPE=Release

            - name: Save CMake Build Cache
              uses: actions/cache/save@v4
              if: always() && env.CMAKE_BUILD_CACHE_RESTORE_KEY != env.CMAKE_BUILD_CACHE_SAVE_KEY
              with:
                  path: ${{ env.CMAKE_BUILD_DIR }}
                  key: ${{ env.CMAKE_BUILD_CACHE_SAVE_KEY }}

            - name: Build
              shell: bash
              run: |
                  cmake \
                    --build ${{ env.CMAKE_BUILD_DIR }} \
                    --config Release
